### ISSUE TITLE
Uncaught TypeError: (0 , _history.createHistory) is not a function

### ISSUE THREAD

**Issue by VinSpee** [electrode-io/electrode-boilerplate-universal-react-node#27]
Hi

Cloning this repo fresh and running `npm i` followed by ` NODE_ENV=development gulp hot` results in this error in the console:

```
Uncaught TypeError: (0 , _history.createHistory) is not a function
```

pointing to this line (29) of `client/app.jsx`:

```
<Router history={createHistory()}>{routes}</Router>
```

any ideas?

**Comment by jchip** [comment]
Hi, thanks for catching this.  This is an issue that was fix in the generator, but the boilerplate was generated before the fix.

This issue is using a custom history has to follow react-router's docs properly here https://github.com/ReactTraining/react-router/blob/master/docs/guides/Histories.md#customize-your-history-further.

The fix for the boilerplate is to remove the use of custom history for now, but we may show properly using a custom history also.

**Comment by VinSpee** [comment]
thanks!

**Comment by jchip** [comment]
should be fixed by https://github.com/electrode-io/electrode-boilerplate-universal-react-node/pull/32

**Comment by ananavati** [comment]
@VinSpee 

would it be okay to close this ticket if you have had a chance to test the fix https://github.com/electrode-io/electrode-boilerplate-universal-react-node/pull/32

**Comment by VinSpee** [comment]
thanks!
